# CI/CD pipeline
name: CI/CD Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkouts the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4
      # sets up the ruby environment
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # caches the gems
      - name: Cache gems
        uses: actions/cache@v3
        with:
          path: |
            vendor/bundle
            ~/.bundle
          key: ${{runner.os}}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # cache npm packages
      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node=${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # installs the dependencies
      - name: Install Dependencies
        run: |
          bundle install --jobs 4 --retry 3
      # Install Nodejs Dependencies
      - name: Install Node.js Dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          else
            npm init -y
            npm install express http-proxy-middleware
      # rubocop for linting and checking for vulnerbilities
      - name: Run Rubocop (Ruby Linter)
        run: bundle exec rubocop --format progress
      # sets the bin files as executable
      - name: Set execute permissions for bin/rails
        run: |
          chmod +x bin/rails
          mkdir -p bin
          if [! -f bin/server.js ]; then
            touch bin/server.js
          fi
          chmod +x bin/server.js
      # sets up the database
      - name: Setup Database
        run: |
          bin/rails db:create db:schema:load db:migrate
      # runs the rspec test
      - name: Run Tests
        run: |
          bundle exec rspec --exclude-pattern "spec/system/**/*_spec.rb"
        env:
          RAILS_ENV: test

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        run: |
          echo "${SSH_KEY}" > deploy_key.pem
          chmod 600 deploy_key.pem
          scp -o StrictHostKeyChecking=no -i deploy_key.pem  script/deploy.sh ${EC2_USER}@${EC2_HOST}:~/deploy.sh
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${EC2_USER}@${EC2_HOST} "chmod +x ~/deploy.sh"
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${EC2_USER}@${EC2_HOST} "~/deploy.sh '${SECRET_KEY_BASE}'"
          echo 'Deployment completed successfully'

