# CI/CD pipeline
name: CI/CD Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
      - name: Cache gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{runner.os}}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: | 
            ${{ runner.os }}-gems-
      - name: Install Dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop (Ruby Linter)
        run: bundle exec rubocop --format progress

      - name: Setup Database
        run: |
          bin/rails db:create db:schema:load

      - name: Run Tests
        run: |
          bin/rails db:setup
          bundle exec rspec --exclude-pattern "spec/system/**/*_spec.rb"